import { classifyReply, generateDraft } from './ai.js';
import { demoProspects, STATUSES } from './data.js';

const root=document.querySelector('#root');
const KEY='dsu-sales-agent-prospects';
let prospects=load(); let page='dashboard'; let selected='1'; let query=''; let filter='TUTTI'; let draft='';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(demoProspects)}catch{return structuredClone(demoProspects)}}
function save(){localStorage.setItem(KEY,JSON.stringify(prospects))}
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const tone={"LEAD CALDO":'hot',VENDITA:'success',CALL:'purple',INTERESSATO:'blue','NON CONTATTARE':'muted','NON INTERESSATO':'muted','DA ANALIZZARE':'gray',QUALIFICATO:'cyan',CONTATTATO:'amber','HA RISPOSTO':'blue','DA CONTATTARE':'amber','MESSAGGIO DA APPROVARE':'purple'};
const badge=s=>`<span class="badge ${tone[s]||'gray'}">${s==='LEAD CALDO'?'🔥 ':''}${esc(s)}</span>`;
const initials=p=>p.firstName[0]+p.lastName[0];
function shell(content){return `<div class="app"><aside><div class="brand"><div class="brandmark">DSU</div><div><b>SALES AGENT</b><small>DANCE SCHOOL UNIVERSITY</small></div></div><nav><button data-page="dashboard" class="${page==='dashboard'?'active':''}">▦ Dashboard</button><button data-page="prospects" class="${page!=='dashboard'?'active':''}">♙ Prospect <em>${prospects.length}</em></button></nav><div class="aside-note"><b>✦ AI Assistant</b><p>Genera bozze intelligenti. Nessun messaggio viene inviato automaticamente.</p><span>FASE 1 · MODALITÀ SICURA</span></div><div class="operator"><div class="avatar sm">DS</div><div><b>Team DSU</b><small>Operatore</small></div></div></aside><main>${header()}${content}</main></div>`}
function header(){const title=page==='dashboard'?'Dashboard':page==='prospects'?'Prospect':'';return `<header><div>${page==='detail'?'<button class="back" data-page="prospects">← Torna ai prospect</button>':`<h1>${title}</h1><p>${page==='dashboard'?'Panoramica delle attività commerciali':prospects.length+' contatti nel database'}</p>`}</div><div class="header-actions"><div class="search"><span>⌕</span><input id="global-search" placeholder="Cerca prospect..." value="${esc(query)}"></div><button class="icon">♢<i></i></button><button class="primary" id="new-prospect">＋ Nuovo prospect</button></div></header>`}
function rows(list){return `<div class="table"><div class="tr th"><span>PROSPECT</span><span>SCUOLA / CITTÀ</span><span>TIPOLOGIA</span><span>STATO</span><span>INSERITO</span></div>${list.map(p=>`<button class="tr" data-open="${p.id}"><span class="person"><i>${initials(p)}</i><span><b>${esc(p.firstName)} ${esc(p.lastName)}</b><small>${esc(p.email)}</small></span></span><span><b>${esc(p.school)}</b><small>${esc(p.city)}</small></span><span>${esc(p.type)}</span><span>${badge(p.status)}</span><span>${new Date(p.createdAt).toLocaleDateString('it-IT',{day:'2-digit',month:'short'})} <b>›</b></span></button>`).join('')}</div>`}
function dashboard(){const count=(...s)=>prospects.filter(p=>s.includes(p.status)).length;const contacted=count('CONTATTATO','HA RISPOSTO','INTERESSATO','LEAD CALDO','CALL','VENDITA');const replies=count('HA RISPOSTO','INTERESSATO','LEAD CALDO','CALL','VENDITA');const metrics=[['Prospect totali',prospects.length,'Tutti i contatti','users'],['Qualificati',count('QUALIFICATO'),'Pronti al contatto','cyan'],['Contattati',contacted,'Contatti avviati','amber'],['Risposte ricevute',replies,'Conversazioni attive','blue'],['Interessati',count('INTERESSATO'),'Interesse rilevato','blue'],['Lead caldi',count('LEAD CALDO'),'Priorità alta','hot'],['Call',count('CALL'),'Call programmate','purple'],['Vendite',count('VENDITA'),'Programmi venduti','success']];const rr=contacted?Math.round(replies/contacted*100):0,cr=prospects.length?Math.round(count('VENDITA')/prospects.length*100):0;return `<div class="content"><section class="welcome"><div><span>VENERDÌ, 25 SETTEMBRE</span><h2>Buongiorno, Team DSU 👋</h2><p>Ecco come stanno andando le attività commerciali.</p></div><div class="safe"><span>●</span><div><b>Modalità sicura attiva</b><small>Nessun invio automatico</small></div></div></section><div class="metrics">${metrics.map(m=>`<article class="metric ${m[3]}"><div class="metric-icon">${m[3]==='hot'?'🔥':'♙'}</div><span>${m[0]}</span><strong>${m[1]}</strong><small>${m[2]}</small></article>`).join('')}</div><div class="rates"><article><div class="ring" style="--p:${rr}%"><b>${rr}%</b></div><div><span>TASSO DI RISPOSTA</span><h3>Conversazioni avviate</h3><p>${replies} risposte su ${contacted} prospect contattati</p></div></article><article><div class="ring green" style="--p:${cr}%"><b>${cr}%</b></div><div><span>TASSO DI CONVERSIONE</span><h3>Da prospect a vendita</h3><p>${count('VENDITA')} vendita su ${prospects.length} prospect totali</p></div></article></div><section class="panel"><div class="panel-head"><div><h3>Prospect recenti</h3><p>Ultimi contatti aggiunti al database</p></div><button data-page="prospects">Visualizza tutti →</button></div>${rows(prospects.slice(0,5))}</section></div>`}
function list(){const found=prospects.filter(p=>(filter==='TUTTI'||p.status===filter)&&`${p.firstName} ${p.lastName} ${p.school} ${p.city}`.toLowerCase().includes(query.toLowerCase()));return `<div class="content"><section class="panel list-panel"><div class="filters"><div class="search wide">⌕ <input id="list-search" placeholder="Cerca per nome, scuola o città..." value="${esc(query)}"></div><select id="filter"><option value="TUTTI">Tutti gli stati</option>${STATUSES.map(s=>`<option ${filter===s?'selected':''}>${s}</option>`).join('')}</select></div>${rows(found)}${found.length?'':'<div class="empty">Nessun prospect corrisponde ai filtri.</div>'}</section></div>`}
function detail(){const p=prospects.find(x=>x.id===selected);if(!p){page='prospects';return list()}const info=(l,v)=>`<div><span>${l}</span><b>${esc(v||'—')}</b></div>`;return `<div class="content detail"><section class="profile panel"><div class="profile-main"><div class="avatar">${initials(p)}</div><div><div class="inline"><h2>${esc(p.firstName)} ${esc(p.lastName)}</h2>${badge(p.status)}</div><p>${esc(p.type)} · ${esc(p.school)}</p></div></div><label>STATO DEL PROSPECT<select id="status">${STATUSES.map(s=>`<option ${p.status===s?'selected':''}>${s}</option>`).join('')}</select></label></section><div class="detail-grid"><div><section class="panel info"><h3>Informazioni di contatto</h3><div class="info-grid">${info('EMAIL',p.email)}${info('CITTÀ',p.city)}${info('SITO WEB',p.website)}${info('INSTAGRAM',p.instagram)}${info('FONTE',p.source)}${info('DATA INSERIMENTO',new Date(p.createdAt).toLocaleDateString('it-IT'))}</div><hr><h4>NOTE</h4><textarea id="notes">${esc(p.notes)}</textarea></section><section class="panel conversation"><div class="panel-head"><div><h3>Storico conversazioni</h3><p>Tutte le interazioni con il prospect</p></div></div>${p.conversations.length?p.conversations.map(c=>`<div class="bubble ${c.direction}"><span>${c.direction==='in'?esc(p.firstName):'Team DSU'}</span><p>${esc(c.text)}</p><small>${c.date}${c.approved?' · ✓ Approvata (non inviata)':''}</small></div>`).join(''):'<div class="empty">Nessuna conversazione registrata.</div>'}</section></div><div class="action-column"><section class="panel simulator"><div class="ai-title"><b>✦</b><div><h3>Simula risposta</h3><p>Testa la classificazione AI</p></div></div><label>RISPOSTA DEL PROSPECT<textarea id="reply" placeholder="Es. Quanto costa?"></textarea></label><div class="quick">${['Quanto costa?','Come funziona?','Possiamo organizzare una call?','Non siamo interessati.'].map(x=>`<button data-quick="${esc(x)}">${esc(x)}</button>`).join('')}</div><div id="classification"></div><button class="primary full" id="simulate" disabled>▣ Registra e genera bozza</button><small class="privacy">Solo simulazione · Nessun messaggio reale</small></section>${draft?draftCard():''}</div></div></div>`}
function draftCard(){return `<section class="panel draft"><div class="draft-head"><span>✦ BOZZA AI</span><b>BOZZA IN ATTESA DI APPROVAZIONE</b></div><textarea id="draft-text">${esc(draft)}</textarea><div><button class="secondary" id="modify">SALVA MODIFICA</button><button class="primary" id="approve">APPROVA</button></div><small>L’approvazione viene solo registrata. Nessun invio reale.</small></section>`}
function modal(){return `<div class="overlay" id="overlay"><form class="modal" id="prospect-form"><div class="modal-head"><div><h2>Nuovo prospect</h2><p>Aggiungi un contatto al database.</p></div><button type="button" id="close">×</button></div><div class="form-grid">${[['firstName','Nome *'],['lastName','Cognome *'],['school','Scuola di danza'],['city','Città'],['email','Email *'],['website','Sito web'],['instagram','Instagram'],['source','Fonte del contatto']].map(([k,l])=>`<label>${l}<input name="${k}" ${l.includes('*')?'required':''}></label>`).join('')}<label>Tipologia<select name="type"><option>Insegnante</option><option>Scuola</option><option>Altro</option></select></label><label class="span2">Note<textarea name="notes"></textarea></label></div><div class="modal-actions"><button type="button" class="secondary" id="cancel">Annulla</button><button class="primary">Aggiungi prospect</button></div></form></div>`}
function render(){root.innerHTML=shell(page==='dashboard'?dashboard():page==='prospects'?list():detail());bind()}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{selected=b.dataset.open;page='detail';draft='';render();scrollTo(0,0)});document.querySelector('#new-prospect').onclick=()=>{document.body.insertAdjacentHTML('beforeend',modal());bindModal()};const gs=document.querySelector('#global-search');if(gs)gs.onchange=e=>{query=e.target.value;page='prospects';render()};const ls=document.querySelector('#list-search');if(ls)ls.oninput=e=>{query=e.target.value;render();const next=document.querySelector('#list-search');next.focus();next.setSelectionRange(query.length,query.length)};const fs=document.querySelector('#filter');if(fs)fs.onchange=e=>{filter=e.target.value;render()};if(page==='detail')bindDetail()}
function bindModal(){const close=()=>document.querySelector('#overlay')?.remove();document.querySelector('#close').onclick=close;document.querySelector('#cancel').onclick=close;document.querySelector('#prospect-form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const p={...f,id:crypto.randomUUID(),createdAt:new Date().toISOString().slice(0,10),status:'DA ANALIZZARE',conversations:[]};prospects.unshift(p);save();close();selected=p.id;page='detail';render()}}
function bindDetail(){const p=prospects.find(x=>x.id===selected);document.querySelector('#status').onchange=e=>{p.status=e.target.value;save();render()};document.querySelector('#notes').onchange=e=>{p.notes=e.target.value;save()};const reply=document.querySelector('#reply'),button=document.querySelector('#simulate'),result=document.querySelector('#classification');const classify=()=>{button.disabled=!reply.value.trim();if(!reply.value.trim()){result.innerHTML='';return}const c=classifyReply(reply.value);result.innerHTML=`<div class="classification ${c.hot?'is-hot':''}">${c.hot?'<b>🔥 LEAD CALDO — INTERVENTO UMANO CONSIGLIATO</b>':''}<span>Classificazione: <strong>${c.label}</strong></span><span>Nuovo stato suggerito: ${badge(c.suggestedStatus)}</span></div>`};reply.oninput=classify;document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{reply.value=b.dataset.quick;classify()});button.onclick=()=>{const text=reply.value,c=classifyReply(text);p.status=c.suggestedStatus;p.conversations.push({id:crypto.randomUUID(),direction:'in',text,date:'Adesso'});draft=generateDraft(p,text);save();render()};const dt=document.querySelector('#draft-text');if(dt){document.querySelector('#modify').onclick=()=>{draft=dt.value};document.querySelector('#approve').onclick=()=>{draft=dt.value;p.conversations.push({id:crypto.randomUUID(),direction:'out',text:draft,date:'Adesso',approved:true});p.status='MESSAGGIO DA APPROVARE';draft='';save();render()}}}
render();
