export const STATUSES = ['DA ANALIZZARE','QUALIFICATO','DA CONTATTARE','MESSAGGIO DA APPROVARE','CONTATTATO','HA RISPOSTO','INTERESSATO','LEAD CALDO','CALL','VENDITA','NON INTERESSATO','NON CONTATTARE'];
export const demoProspects = [
 {id:'1',firstName:'Giulia',lastName:'Rossi',school:'Spazio Danza Milano',city:'Milano',email:'giulia.rossi@example.com',website:'spaziodanza.example',instagram:'@spaziodanza_demo',type:'Scuola',source:'Evento di settore',notes:'Dirige una scuola con 8 insegnanti. Interessata alla formazione del team.',createdAt:'2026-09-18',status:'LEAD CALDO',conversations:[{id:'c1',direction:'out',text:'Ciao Giulia, ti presento il percorso professionale DSU Dance Teacher Program.',date:'18 set, 10:30',approved:true},{id:'c2',direction:'in',text:'Possiamo iscrivere più insegnanti? Possiamo organizzare una call?',date:'19 set, 09:15'}]},
 {id:'2',firstName:'Marco',lastName:'Bianchi',school:'Move Lab',city:'Bologna',email:'marco.bianchi@example.com',website:'movelab.example',instagram:'@movelab_demo',type:'Insegnante',source:'Instagram',notes:'Insegna hip hop da tre anni.',createdAt:'2026-09-20',status:'INTERESSATO',conversations:[{id:'c3',direction:'in',text:'Come funziona il programma e quanto costa?',date:'21 set, 15:40'}]},
 {id:'3',firstName:'Elena',lastName:'De Luca',school:'Étoile Academy',city:'Roma',email:'elena.deluca@example.com',website:'etoile.example',instagram:'@etoile_demo',type:'Scuola',source:'Referral',notes:'Contatto suggerito da un docente DSU.',createdAt:'2026-09-21',status:'CALL',conversations:[]},
 {id:'4',firstName:'Sara',lastName:'Conti',school:'—',city:'Firenze',email:'sara.conti@example.com',website:'',instagram:'@sara_dance_demo',type:'Insegnante',source:'Form sito',notes:'Dancer in transizione verso l’insegnamento.',createdAt:'2026-09-22',status:'QUALIFICATO',conversations:[]},
 {id:'5',firstName:'Luca',lastName:'Esposito',school:'Urban Beat',city:'Napoli',email:'luca.esposito@example.com',website:'urbanbeat.example',instagram:'@urbanbeat_demo',type:'Scuola',source:'Ricerca manuale',notes:'Non ricontattare su richiesta.',createdAt:'2026-09-12',status:'NON CONTATTARE',conversations:[{id:'c5',direction:'in',text:'Vi chiedo di non contattarmi più.',date:'14 set, 11:00'}]},
 {id:'6',firstName:'Martina',lastName:'Ferrari',school:'Danza Viva',city:'Torino',email:'martina.ferrari@example.com',website:'danzaviva.example',instagram:'@danzaviva_demo',type:'Insegnante',source:'Workshop',notes:'Ha chiesto informazioni dopo il workshop.',createdAt:'2026-09-23',status:'CONTATTATO',conversations:[]},
 {id:'7',firstName:'Paolo',lastName:'Ricci',school:'Studio R',city:'Padova',email:'paolo.ricci@example.com',website:'studior.example',instagram:'@studior_demo',type:'Altro',source:'Newsletter',notes:'Collaboratore esterno di una scuola.',createdAt:'2026-09-24',status:'VENDITA',conversations:[]},
 {id:'8',firstName:'Anna',lastName:'Gallo',school:'Next Step',city:'Bari',email:'anna.gallo@example.com',website:'nextstep.example',instagram:'@nextstep_demo',type:'Insegnante',source:'Instagram',notes:'Da analizzare.',createdAt:'2026-09-25',status:'DA ANALIZZARE',conversations:[]}
];
